import { useState, useEffect } from 'react';
import { ArrowLeftRight, TrendingUp, TrendingDown, Minus, Download, Copy, RotateCcw, FileText, Loader, AlertTriangle, CheckCircle } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, Legend } from 'recharts';
import { useNavigate } from 'react-router-dom';
import { API_BASE_URL } from '../constants';


export default function ComparisonPanel() {
  const [comparisonData, setComparisonData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [optimizedConfig, setOptimizedConfig] = useState<any>(null);
  const [baselineConfig, setBaselineConfig] = useState<any>(null);
  const [trainingSummary, setTrainingSummary] = useState<any>(null);
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    const optRaw = localStorage.getItem('inframind_optimized_config');
    const summaryRaw = localStorage.getItem('inframind_training_summary');
    if (optRaw) {
      try {
        const parsed = JSON.parse(optRaw);
        setOptimizedConfig(parsed);
        if (summaryRaw) setTrainingSummary(JSON.parse(summaryRaw));
        runComparison(parsed);
      } catch (e) {
        console.error('Failed to parse stored config:', e);
      }
    }
  }, []);

  const runComparison = async (optConfig: any) => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch(`${API_BASE_URL}/api/compare`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          baseline_config: {},  // Empty = use DAG defaults on the backend
          optimized_config: optConfig,
          workload_type: 'bursty',
          duration_s: 300,
        }),
      });
      const data = await res.json();
      if (res.ok) {
        setComparisonData(data);
        if (data.baseline_config) setBaselineConfig(data.baseline_config);
      } else {
        setError(data.detail || 'Comparison failed');
      }
    } catch (e: any) {
      setError(e.message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopyJSON = () => {
    if (optimizedConfig) {
      navigator.clipboard.writeText(JSON.stringify(optimizedConfig, null, 2));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadTf = () => {
    if (!optimizedConfig) return;
    let tf = `# InfraMIND v4 — Optimized Configuration\n# Generated by RL Bayesian Optimizer\n\nprovider "aws" {\n  region = var.aws_region\n}\n\nvariable "aws_region" {\n  default = "us-east-1"\n}\n\n`;
    for (const [svc, params] of Object.entries(optimizedConfig) as any) {
      tf += `# Service: ${svc}\nresource "aws_ecs_service" "${svc}" {\n  name            = "${svc}"\n  desired_count   = ${params.replicas}\n  cpu             = ${params.cpu_millicores}\n  memory          = ${params.memory_mb}\n}\n\n`;
    }
    const blob = new Blob([tf], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'optimized_infra.tf';
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!optimizedConfig) {
    return (
      <div className="flex flex-col items-center justify-center h-[80vh] text-gray-400 gap-4">
        <ArrowLeftRight size={48} className="text-gray-600 mb-2" />
        <h2 className="text-xl text-white">No Optimization Data</h2>
        <p>Run RL Training first. The optimizer will find the best configuration.</p>
        <button onClick={() => navigate('/training')} className="mt-4 px-6 py-2 bg-accent-purple/20 text-accent-purple border border-accent-purple rounded-lg hover:bg-accent-purple/30">
          Go to RL Training
        </button>
      </div>
    );
  }

  // Build chart data
  const normalize = (base: number, opt: number) => {
      if (base === 0 && opt === 0) return 100;
      if (base === 0) return opt > 0 ? 200 : 100; // Arbitrary 2x jump if base is zero but opt is positive
      return Math.round((opt / base) * 100);
  };

  const chartData = comparisonData ? [
    { 
        metric: 'P99 Latency', 
        baseline: 100, 
        optimized: normalize(comparisonData.baseline.p99_latency_ms, comparisonData.optimized.p99_latency_ms) 
    },
    { 
        metric: 'Cost', 
        baseline: 100, 
        optimized: normalize(comparisonData.baseline.cost_estimate, comparisonData.optimized.cost_estimate) 
    },
    { 
        metric: 'SLA Violations', 
        baseline: 100, 
        optimized: normalize(comparisonData.baseline.sla_violations_pct, comparisonData.optimized.sla_violations_pct) 
    },
  ] : [];

  const services = Object.keys(optimizedConfig);

  return (
    <div className="h-full flex flex-col gap-6 pb-8 overflow-y-auto pr-4">

      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-3">
            <ArrowLeftRight className="text-accent-cyan" /> Before vs. After
          </h2>
          <p className="text-gray-400 text-sm mt-1">RL Optimization Results — Baseline vs. Pareto-Optimal Configuration</p>
        </div>
        {trainingSummary && (
          <div className="flex items-center gap-2 bg-accent-green/10 border border-accent-green/30 text-accent-green px-4 py-2 rounded-lg text-sm font-medium">
            <CheckCircle size={16} /> Training Complete — Best Reward: {trainingSummary.best_reward?.toFixed?.(2) || trainingSummary.best_reward}
          </div>
        )}
      </div>

      {/* Loading / Error State */}
      {isLoading && (
        <div className="glass-panel p-8 flex items-center justify-center gap-3 text-gray-400">
          <Loader className="animate-spin text-accent-purple" size={24} />
          Running both simulations for fair comparison...
        </div>
      )}
      {error && (
        <div className="bg-accent-red/10 border border-accent-red/30 text-accent-red p-4 rounded-lg flex items-center gap-2">
          <AlertTriangle size={18} /> {error}
        </div>
      )}

      {comparisonData && (
        <>
          {/* Metric Comparison Bar Chart */}
          <div className="glass-panel p-6">
            <h3 className="text-xs font-medium text-gray-400 tracking-widest uppercase mb-4">Metric Comparison (% of Baseline)</h3>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} layout="vertical" barGap={4} barSize={18}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#222" horizontal={false} />
                  <XAxis type="number" stroke="#555" tick={{ fill: '#666', fontSize: 12 }} domain={[0, 'dataMax + 10']} />
                  <YAxis dataKey="metric" type="category" stroke="#555" tick={{ fill: '#aaa', fontSize: 12 }} width={140} />
                  <Tooltip contentStyle={{ backgroundColor: '#0a0a1f', borderColor: '#333', borderRadius: '8px' }} />
                  <Legend />
                  <Bar dataKey="baseline" name="Baseline" fill="#6b7280" radius={[0, 4, 4, 0]} />
                  <Bar dataKey="optimized" name="Optimized" fill="#8b5cf6" radius={[0, 4, 4, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Delta Badges */}
            <div className="grid grid-cols-4 gap-4 mt-4">
              {[
                { label: 'P99 Latency', val: comparisonData.deltas.p99_change_pct, unit: '%', invert: true },
                { label: 'Cost', val: comparisonData.deltas.cost_change_pct, unit: '%', invert: false },
                { label: 'SLA Violations', val: comparisonData.deltas.sla_change_pct, unit: '%', invert: true },
              ].map((d) => {
                const isGood = d.invert ? d.val <= 0 : d.val <= 0;
                const Icon = d.val < 0 ? TrendingDown : d.val > 0 ? TrendingUp : Minus;
                return (
                  <div key={d.label} className={`p-3 rounded-lg border text-center ${isGood ? 'bg-accent-green/10 border-accent-green/30 text-accent-green' : 'bg-accent-red/10 border-accent-red/30 text-accent-red'}`}>
                    <div className="text-xs text-gray-400 mb-1">{d.label}</div>
                    <div className="text-lg font-bold flex items-center justify-center gap-1">
                      <Icon size={16} /> {d.val > 0 ? '+' : ''}{d.val}{d.unit}
                    </div>
                  </div>
                );
              })}
              <div className="p-3 rounded-lg border bg-accent-cyan/10 border-accent-cyan/30 text-accent-cyan text-center">
                <div className="text-xs text-gray-400 mb-1">Dropped Reqs</div>
                <div className="text-lg font-bold flex items-center justify-center gap-1">
                  <Minus size={16} /> {comparisonData.optimized.dropped_requests}
                </div>
              </div>
            </div>
          </div>

          {/* Config Diff */}
          <div className="glass-panel p-6">
            <h3 className="text-xs font-medium text-gray-400 tracking-widest uppercase mb-4">Configuration Diff — Per Service</h3>
            <div className="grid grid-cols-2 gap-6">
              {/* Baseline Column */}
              <div>
                <div className="text-sm font-semibold text-gray-500 mb-3 uppercase tracking-wider border-b border-gray-800 pb-2">Baseline</div>
                {services.map(svc => (
                  <div key={svc} className="bg-black/30 border border-gray-800 rounded-lg p-4 mb-3">
                    <div className="text-white font-mono font-medium mb-2">{svc}</div>
                    {Object.entries((baselineConfig || {})[svc] || {}).map(([key, val]) => (
                      <div key={key} className="flex justify-between text-sm py-1 border-b border-gray-800/50 last:border-none">
                        <span className="text-gray-500">{key}</span>
                        <span className="text-gray-300 font-mono">{val as any}</span>
                      </div>
                    ))}
                  </div>
                ))}
              </div>

              {/* Optimized Column */}
              <div>
                <div className="text-sm font-semibold text-accent-purple mb-3 uppercase tracking-wider border-b border-accent-purple/30 pb-2">Optimized</div>
                {services.map(svc => (
                  <div key={svc} className="bg-accent-purple/5 border border-accent-purple/20 rounded-lg p-4 mb-3">
                    <div className="text-white font-mono font-medium mb-2">{svc}</div>
                    {Object.entries(optimizedConfig[svc] || {}).map(([key, val]) => {
                      const baseVal = (baselineConfig || {})[svc]?.[key];
                      const changed = baseVal !== val;
                      const delta = typeof val === 'number' && typeof baseVal === 'number' ? (val as number) - baseVal : null;
                      return (
                        <div key={key} className={`flex justify-between text-sm py-1 border-b border-gray-800/50 last:border-none ${changed ? 'bg-accent-purple/10 -mx-2 px-2 rounded' : ''}`}>
                          <span className="text-gray-500">{key}</span>
                          <div className="flex items-center gap-2">
                            <span className={`font-mono ${changed ? 'text-white font-bold' : 'text-gray-300'}`}>{val as any}</span>
                            {changed && delta !== null && (
                              <span className={`text-xs font-mono px-1.5 py-0.5 rounded ${delta > 0 ? 'bg-accent-green/20 text-accent-green' : 'bg-accent-red/20 text-accent-red'}`}>
                                {delta > 0 ? '↑' : '↓'} {delta > 0 ? '+' : ''}{delta}
                              </span>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Trade-off Insight */}
          <div className="glass-panel p-5 border-l-4 border-accent-gold bg-accent-gold/5">
            <div className="flex items-start gap-3">
              <div className="text-2xl">🧠</div>
              <div>
                <div className="text-accent-gold font-semibold text-sm mb-1 uppercase tracking-wider">Optimization Insight</div>
                <p className="text-gray-300 leading-relaxed">{comparisonData.insight}</p>
              </div>
            </div>
          </div>

          {/* Export Actions */}
          <div className="glass-panel p-4 flex gap-4 items-center flex-wrap">
            <button onClick={handleDownloadTf} className="bg-accent-green/15 hover:bg-accent-green/25 text-accent-green border border-accent-green/40 px-5 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all">
              <Download size={16} /> Download Optimized .tf
            </button>
            <button onClick={handleCopyJSON} className="bg-accent-cyan/15 hover:bg-accent-cyan/25 text-accent-cyan border border-accent-cyan/40 px-5 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all">
              <Copy size={16} /> {copied ? 'Copied!' : 'Copy Config JSON'}
            </button>
            <button onClick={() => navigate('/training')} className="bg-accent-purple/15 hover:bg-accent-purple/25 text-accent-purple border border-accent-purple/40 px-5 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all">
              <RotateCcw size={16} /> Re-run Training
            </button>
            <button className="bg-accent-orange/15 hover:bg-accent-orange/25 text-accent-orange border border-accent-orange/40 px-5 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all ml-auto">
              <FileText size={16} /> Export Report
            </button>
          </div>
        </>
      )}
    </div>
  );
}
