import { useState, useEffect, useRef } from 'react';
import { BarChart3, Play, Square, Pause, Settings2, ArrowRight } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { useNavigate } from 'react-router-dom';
import { WS_BASE_URL, WEIGHT_SLIDERS, DEFAULT_WEIGHTS } from '../constants';

export default function TrainingDashboard() {
  const [status, setStatus] = useState('stopped');
  const [epoch, setEpoch] = useState(0);
  const [rewardData, setRewardData] = useState<any[]>([]);
  const wsRef = useRef<WebSocket | null>(null);
  const navigate = useNavigate();

  const [weights, setWeights] = useState(DEFAULT_WEIGHTS);

  useEffect(() => {
    wsRef.current = new WebSocket(`${WS_BASE_URL}/api/ws/training`);
    
    wsRef.current.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.status === 'completed') {
            setStatus('completed');
            // Persist the actual optimized config generated by the backend
            if (data.optimized_config) {
              localStorage.setItem('inframind_optimized_config', JSON.stringify(data.optimized_config));
            }
            localStorage.setItem('inframind_training_summary', JSON.stringify({
              best_reward: data.best_reward || 0,
              total_epochs: data.total_epochs || 100,
            }));
        } else {
            setEpoch(data.epoch);
            if (data.reward) {
                setRewardData(prev => {
                    const newArray = [...prev, { epoch: data.epoch, reward: data.reward, loss: data.loss }];
                    return newArray.slice(-30); // keep last 30
                });
            }
        }
      } catch (e) {
        console.error('Failed to parse training WS message:', e);
      }
    };

    return () => wsRef.current?.close();
  }, []);

  const handleStart = () => {
    setRewardData([]);
    setStatus('running');
    wsRef.current?.send(JSON.stringify({ type: 'START', config: { ...weights, epochs: 100 } }));
  };

  const handleStop = () => {
    setStatus('stopped');
    wsRef.current?.send(JSON.stringify({ type: 'STOP' }));
  };

  const handleWeightChange = (key: string, val: number) => {
    const newW = { ...weights, [key]: val };
    setWeights(newW);
    if (status === 'running') {
        wsRef.current?.send(JSON.stringify({ type: 'UPDATE_WEIGHTS', config: newW }));
    }
  };

  return (
    <div className="h-full flex flex-col gap-6">
      <div className="flex justify-between items-center">
          <h2 className="text-2xl font-bold flex items-center gap-2"><BarChart3 className="text-accent-purple" /> RL Training</h2>
          <div className="flex gap-3">
              {status === 'running' ? (
                  <button onClick={handleStop} className="bg-red-500/20 text-red-500 border border-red-500/50 hover:bg-red-500/30 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-all">
                      <Square size={16} /> Stop Training
                  </button>
              ) : (
                  <button onClick={handleStart} className="bg-accent-purple/20 text-accent-purple border border-accent-purple/50 hover:bg-accent-purple/30 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-all">
                      <Play size={16} /> Start Training
                  </button>
              )}
              {status === 'completed' && (
                  <button onClick={() => navigate('/compare')} className="bg-accent-green/20 text-accent-green border border-accent-green/50 hover:bg-accent-green/30 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-all">
                      <ArrowRight size={16} /> View Comparison
                  </button>
              )}
          </div>
      </div>

      <div className="grid grid-cols-4 gap-6 h-full">
        {/* Main Chart Area */}
        <div className="col-span-3 flex flex-col gap-6">
            <div className="glass-panel p-6 flex-1">
                <h3 className="text-gray-400 font-medium mb-4 uppercase text-sm tracking-wider">Reward Convergence Curve</h3>
                <div className="h-64 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={rewardData}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                            <XAxis dataKey="epoch" stroke="#666" tick={{fill: '#666'}} />
                            <YAxis yAxisId="left" stroke="#8b5cf6" tick={{fill: '#666'}} />
                            <Tooltip contentStyle={{backgroundColor: '#0a0a1f', borderColor: '#333', borderRadius: '8px'}} />
                            <Line yAxisId="left" type="monotone" dataKey="reward" stroke="#8b5cf6" strokeWidth={2} dot={false} activeDot={{r: 6}} />
                        </LineChart>
                    </ResponsiveContainer>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-6">
                <div className="glass-panel p-5">
                    <h4 className="text-gray-500 text-xs mb-1 uppercase">Current Epoch</h4>
                    <div className="text-2xl text-white font-mono">{epoch} / 100</div>
                </div>
                <div className="glass-panel p-5">
                    <h4 className="text-gray-500 text-xs mb-1 uppercase">Best Reward</h4>
                    <div className="text-2xl text-accent-green font-mono">
                        {rewardData.length > 0 ? Math.max(...rewardData.map(d=>d.reward)).toFixed(2) : '--'}
                    </div>
                </div>
                <div className="glass-panel p-5">
                    <h4 className="text-gray-500 text-xs mb-1 uppercase">Current Loss</h4>
                    <div className="text-2xl text-accent-red font-mono">
                        {rewardData.length > 0 ? rewardData[rewardData.length-1].loss.toFixed(2) : '--'}
                    </div>
                </div>
            </div>
        </div>

        {/* Weights Controls */}
        <div className="col-span-1 glass-panel p-6">
            <h3 className="text-white font-medium mb-6 flex items-center gap-2"><Settings2 size={18} /> Objective Weights</h3>
            
            <div className="flex flex-col gap-6">
                {WEIGHT_SLIDERS.map(w => (
                    <div key={w.key}>
                        <div className="flex justify-between text-sm mb-2">
                            <span className="text-gray-300">{w.label} <span className="text-gray-600 font-mono text-xs">({w.key})</span></span>
                            <span className="text-white font-mono">{(weights as any)[w.key].toFixed(2)}</span>
                        </div>
                        <input 
                            type="range" min="0" max="1" step="0.05"
                            value={(weights as any)[w.key]}
                            onChange={(e) => handleWeightChange(w.key, parseFloat(e.target.value))}
                            className={`w-full h-1 ${w.color} rounded-lg appearance-none cursor-pointer`}
                        />
                    </div>
                ))}
            </div>
            
            <div className="mt-8 p-4 bg-accent-blue/10 rounded-lg border border-accent-blue/20">
                <p className="text-xs text-accent-blue/80 font-medium tracking-wide">ADAPTIVE TURBO OPTIMIZER</p>
                <p className="text-xs text-gray-400 mt-2 leading-relaxed">
                    Adjusting these weights recalculates the scalarization of the Pareto frontier in real-time, steering the Trust Region Bayesian Optimization towards your preferred trade-offs.
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}
